TARGETS = \
		oversee.h.c	\
		oversee_env.h.c	\
		oversee_platform.h.c	\
		oversee_platform_types.h.c	\
		oversee_result_stream_api.h.c	\
		oversee_result_stream_types.h.c	\
		oversee_types.h.c	\


OBJECTS = ${TARGETS:.c=.o}

all:	${OBJECTS}
